{% set name = "xxh-xxh" %}
{% set version = "0.8.7" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 3608144e2035b7d3a8a24873b3dd74ea1b4460892971e265506fd46274ad2973

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python
    - pip
  run:
    - python
    - pexpect
    - pyyaml

test:
  imports:
    - xxh_xxh

about:
  home: https://github.com/xxh/xxh
  license: BSD-2-Clause
  license_family: BSD
  license_file: LICENSE
  summary: Bring your favorite shell wherever you go through the ssh
  doc_url: https://github.com/xxh/xxh/blob/master/README.md
  dev_url: https://github.com/xxh/xxh

extra:
  recipe-maintainers:
    - scopatz
